### ISSUE TITLE
Bug found on sorting algorithms

### ISSUE THREAD

**Issue by pablocanones** [cacheaudit/cacheaudit#2]
When running a sorting algorithm the following message appears:
Fatal error: exception Assert_failure("cacheaudit.ml", 152, 18)

The bug occurs since

commit 776ef5331cdcc3b83f819e54a271b035838338d9
Author: Goran Doychev <g.doychev@gmail.com>
Date:   Wed Aug 12 17:15:20 2015 +0200
    Restructuring parsing of configuration file. Allow missing parameters, as well as specifying the end address.

**Comment by gdoychev** [comment]
Can you specify the parameters/config files you are using?

**Comment by pablocanones** [comment]
The error occurs on any of the three executables of the examples/Sorting folder without any extra parameters. I'm runing the current versions on github.
